version: '3.1'

volumes:
  pgdata:
    driver: local

services:
  db:
    image: postgres:13
    command: [ "postgres", "-c", "log_statement=all" ]
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data